// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/order_completed.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCompletedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode     string                 `protobuf:"bytes,3,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	DiscountAmount float64                `protobuf:"fixed64,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	CompletedAt    int64                  `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderCompletedEvent) Reset() {
	*x = OrderCompletedEvent{}
	mi := &file_proto_order_completed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompletedEvent) ProtoMessage() {}

func (x *OrderCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_completed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompletedEvent.ProtoReflect.Descriptor instead.
func (*OrderCompletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_order_completed_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCompletedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCompletedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCompletedEvent) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *OrderCompletedEvent) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *OrderCompletedEvent) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

var File_proto_order_completed_proto protoreflect.FileDescriptor

const file_proto_order_completed_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/order_completed.proto\x12\fcoupon.event\"\xb6\x01\n" +
	"\x13OrderCompletedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x03 \x01(\tR\n" +
	"couponCode\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x01R\x0ediscountAmount\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\x03R\vcompletedAtB5Z3dift_user_insentive/user-coupon-service/proto/pb;pbb\x06proto3"

var (
	file_proto_order_completed_proto_rawDescOnce sync.Once
	file_proto_order_completed_proto_rawDescData []byte
)

func file_proto_order_completed_proto_rawDescGZIP() []byte {
	file_proto_order_completed_proto_rawDescOnce.Do(func() {
		file_proto_order_completed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_completed_proto_rawDesc), len(file_proto_order_completed_proto_rawDesc)))
	})
	return file_proto_order_completed_proto_rawDescData
}

var file_proto_order_completed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_order_completed_proto_goTypes = []any{
	(*OrderCompletedEvent)(nil), // 0: coupon.event.OrderCompletedEvent
}
var file_proto_order_completed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_completed_proto_init() }
func file_proto_order_completed_proto_init() {
	if File_proto_order_completed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_completed_proto_rawDesc), len(file_proto_order_completed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_order_completed_proto_goTypes,
		DependencyIndexes: file_proto_order_completed_proto_depIdxs,
		MessageInfos:      file_proto_order_completed_proto_msgTypes,
	}.Build()
	File_proto_order_completed_proto = out.File
	file_proto_order_completed_proto_goTypes = nil
	file_proto_order_completed_proto_depIdxs = nil
}
