// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/order_failed.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FailedAt      int64                  `protobuf:"varint,4,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFailedEvent) Reset() {
	*x = OrderFailedEvent{}
	mi := &file_proto_order_failed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFailedEvent) ProtoMessage() {}

func (x *OrderFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_failed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFailedEvent.ProtoReflect.Descriptor instead.
func (*OrderFailedEvent) Descriptor() ([]byte, []int) {
	return file_proto_order_failed_proto_rawDescGZIP(), []int{0}
}

func (x *OrderFailedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderFailedEvent) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *OrderFailedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderFailedEvent) GetFailedAt() int64 {
	if x != nil {
		return x.FailedAt
	}
	return 0
}

var File_proto_order_failed_proto protoreflect.FileDescriptor

const file_proto_order_failed_proto_rawDesc = "" +
	"\n" +
	"\x18proto/order_failed.proto\x12\x02pb\"\x84\x01\n" +
	"\x10OrderFailedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x02 \x01(\tR\n" +
	"couponCode\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1b\n" +
	"\tfailed_at\x18\x04 \x01(\x03R\bfailedAtB5Z3dift_user_insentive/user-coupon-service/proto/pb;pbb\x06proto3"

var (
	file_proto_order_failed_proto_rawDescOnce sync.Once
	file_proto_order_failed_proto_rawDescData []byte
)

func file_proto_order_failed_proto_rawDescGZIP() []byte {
	file_proto_order_failed_proto_rawDescOnce.Do(func() {
		file_proto_order_failed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_failed_proto_rawDesc), len(file_proto_order_failed_proto_rawDesc)))
	})
	return file_proto_order_failed_proto_rawDescData
}

var file_proto_order_failed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_order_failed_proto_goTypes = []any{
	(*OrderFailedEvent)(nil), // 0: pb.OrderFailedEvent
}
var file_proto_order_failed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_failed_proto_init() }
func file_proto_order_failed_proto_init() {
	if File_proto_order_failed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_failed_proto_rawDesc), len(file_proto_order_failed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_order_failed_proto_goTypes,
		DependencyIndexes: file_proto_order_failed_proto_depIdxs,
		MessageInfos:      file_proto_order_failed_proto_msgTypes,
	}.Build()
	File_proto_order_failed_proto = out.File
	file_proto_order_failed_proto_goTypes = nil
	file_proto_order_failed_proto_depIdxs = nil
}
