// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.0
// source: proto/order_service_call.proto

package usercoupon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserCouponService_GetUserCoupons_FullMethodName = "/usercoupon.UserCouponService/GetUserCoupons"
	UserCouponService_ValidateCoupon_FullMethodName = "/usercoupon.UserCouponService/ValidateCoupon"
	UserCouponService_ReserveCoupon_FullMethodName  = "/usercoupon.UserCouponService/ReserveCoupon"
	UserCouponService_ReleaseCoupon_FullMethodName  = "/usercoupon.UserCouponService/ReleaseCoupon"
)

// UserCouponServiceClient is the client API for UserCouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCouponServiceClient interface {
	// -------------------------
	// READ
	// -------------------------
	GetUserCoupons(ctx context.Context, in *GetUserCouponsRequest, opts ...grpc.CallOption) (*GetUserCouponsResponse, error)
	ValidateCoupon(ctx context.Context, in *ValidateCouponRequest, opts ...grpc.CallOption) (*ValidateCouponResponse, error)
	// -------------------------
	// WRITE
	// -------------------------
	ReserveCoupon(ctx context.Context, in *ReserveCouponRequest, opts ...grpc.CallOption) (*ReserveCouponResponse, error)
	// 🔥 (แนะนำเพิ่ม) เผื่อใช้ในอนาคต / manual release
	ReleaseCoupon(ctx context.Context, in *ReleaseCouponRequest, opts ...grpc.CallOption) (*ReleaseCouponResponse, error)
}

type userCouponServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCouponServiceClient(cc grpc.ClientConnInterface) UserCouponServiceClient {
	return &userCouponServiceClient{cc}
}

func (c *userCouponServiceClient) GetUserCoupons(ctx context.Context, in *GetUserCouponsRequest, opts ...grpc.CallOption) (*GetUserCouponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCouponsResponse)
	err := c.cc.Invoke(ctx, UserCouponService_GetUserCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCouponServiceClient) ValidateCoupon(ctx context.Context, in *ValidateCouponRequest, opts ...grpc.CallOption) (*ValidateCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCouponResponse)
	err := c.cc.Invoke(ctx, UserCouponService_ValidateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCouponServiceClient) ReserveCoupon(ctx context.Context, in *ReserveCouponRequest, opts ...grpc.CallOption) (*ReserveCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveCouponResponse)
	err := c.cc.Invoke(ctx, UserCouponService_ReserveCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCouponServiceClient) ReleaseCoupon(ctx context.Context, in *ReleaseCouponRequest, opts ...grpc.CallOption) (*ReleaseCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseCouponResponse)
	err := c.cc.Invoke(ctx, UserCouponService_ReleaseCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCouponServiceServer is the server API for UserCouponService service.
// All implementations must embed UnimplementedUserCouponServiceServer
// for forward compatibility.
type UserCouponServiceServer interface {
	// -------------------------
	// READ
	// -------------------------
	GetUserCoupons(context.Context, *GetUserCouponsRequest) (*GetUserCouponsResponse, error)
	ValidateCoupon(context.Context, *ValidateCouponRequest) (*ValidateCouponResponse, error)
	// -------------------------
	// WRITE
	// -------------------------
	ReserveCoupon(context.Context, *ReserveCouponRequest) (*ReserveCouponResponse, error)
	// 🔥 (แนะนำเพิ่ม) เผื่อใช้ในอนาคต / manual release
	ReleaseCoupon(context.Context, *ReleaseCouponRequest) (*ReleaseCouponResponse, error)
	mustEmbedUnimplementedUserCouponServiceServer()
}

// UnimplementedUserCouponServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserCouponServiceServer struct{}

func (UnimplementedUserCouponServiceServer) GetUserCoupons(context.Context, *GetUserCouponsRequest) (*GetUserCouponsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCoupons not implemented")
}
func (UnimplementedUserCouponServiceServer) ValidateCoupon(context.Context, *ValidateCouponRequest) (*ValidateCouponResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCoupon not implemented")
}
func (UnimplementedUserCouponServiceServer) ReserveCoupon(context.Context, *ReserveCouponRequest) (*ReserveCouponResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveCoupon not implemented")
}
func (UnimplementedUserCouponServiceServer) ReleaseCoupon(context.Context, *ReleaseCouponRequest) (*ReleaseCouponResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseCoupon not implemented")
}
func (UnimplementedUserCouponServiceServer) mustEmbedUnimplementedUserCouponServiceServer() {}
func (UnimplementedUserCouponServiceServer) testEmbeddedByValue()                           {}

// UnsafeUserCouponServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCouponServiceServer will
// result in compilation errors.
type UnsafeUserCouponServiceServer interface {
	mustEmbedUnimplementedUserCouponServiceServer()
}

func RegisterUserCouponServiceServer(s grpc.ServiceRegistrar, srv UserCouponServiceServer) {
	// If the following call panics, it indicates UnimplementedUserCouponServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserCouponService_ServiceDesc, srv)
}

func _UserCouponService_GetUserCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponServiceServer).GetUserCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCouponService_GetUserCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponServiceServer).GetUserCoupons(ctx, req.(*GetUserCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCouponService_ValidateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponServiceServer).ValidateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCouponService_ValidateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponServiceServer).ValidateCoupon(ctx, req.(*ValidateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCouponService_ReserveCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponServiceServer).ReserveCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCouponService_ReserveCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponServiceServer).ReserveCoupon(ctx, req.(*ReserveCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCouponService_ReleaseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponServiceServer).ReleaseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCouponService_ReleaseCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponServiceServer).ReleaseCoupon(ctx, req.(*ReleaseCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCouponService_ServiceDesc is the grpc.ServiceDesc for UserCouponService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCouponService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usercoupon.UserCouponService",
	HandlerType: (*UserCouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserCoupons",
			Handler:    _UserCouponService_GetUserCoupons_Handler,
		},
		{
			MethodName: "ValidateCoupon",
			Handler:    _UserCouponService_ValidateCoupon_Handler,
		},
		{
			MethodName: "ReserveCoupon",
			Handler:    _UserCouponService_ReserveCoupon_Handler,
		},
		{
			MethodName: "ReleaseCoupon",
			Handler:    _UserCouponService_ReleaseCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/order_service_call.proto",
}
