// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/order_service_call.proto

package usercoupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCouponsRequest) Reset() {
	*x = GetUserCouponsRequest{}
	mi := &file_proto_order_service_call_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCouponsRequest) ProtoMessage() {}

func (x *GetUserCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCouponsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCouponsRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserCouponsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserCouponsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*UserCoupon          `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCouponsResponse) Reset() {
	*x = GetUserCouponsResponse{}
	mi := &file_proto_order_service_call_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCouponsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCouponsResponse) ProtoMessage() {}

func (x *GetUserCouponsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCouponsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCouponsResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserCouponsResponse) GetCoupons() []*UserCoupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

type ValidateCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCouponRequest) Reset() {
	*x = ValidateCouponRequest{}
	mi := &file_proto_order_service_call_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCouponRequest) ProtoMessage() {}

func (x *ValidateCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCouponRequest.ProtoReflect.Descriptor instead.
func (*ValidateCouponRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateCouponRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateCouponRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

type ValidateCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Coupon        *UserCoupon            `protobuf:"bytes,3,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCouponResponse) Reset() {
	*x = ValidateCouponResponse{}
	mi := &file_proto_order_service_call_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCouponResponse) ProtoMessage() {}

func (x *ValidateCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCouponResponse.ProtoReflect.Descriptor instead.
func (*ValidateCouponResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateCouponResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateCouponResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ValidateCouponResponse) GetCoupon() *UserCoupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

type ReserveCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCouponRequest) Reset() {
	*x = ReserveCouponRequest{}
	mi := &file_proto_order_service_call_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCouponRequest) ProtoMessage() {}

func (x *ReserveCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCouponRequest.ProtoReflect.Descriptor instead.
func (*ReserveCouponRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveCouponRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveCouponRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

type ReserveCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCouponResponse) Reset() {
	*x = ReserveCouponResponse{}
	mi := &file_proto_order_service_call_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCouponResponse) ProtoMessage() {}

func (x *ReserveCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCouponResponse.ProtoReflect.Descriptor instead.
func (*ReserveCouponResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveCouponResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveCouponResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReleaseCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCouponRequest) Reset() {
	*x = ReleaseCouponRequest{}
	mi := &file_proto_order_service_call_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCouponRequest) ProtoMessage() {}

func (x *ReleaseCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCouponRequest.ProtoReflect.Descriptor instead.
func (*ReleaseCouponRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseCouponRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReleaseCouponRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

type ReleaseCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCouponResponse) Reset() {
	*x = ReleaseCouponResponse{}
	mi := &file_proto_order_service_call_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCouponResponse) ProtoMessage() {}

func (x *ReleaseCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCouponResponse.ProtoReflect.Descriptor instead.
func (*ReleaseCouponResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseCouponResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseCouponResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UserCoupon struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	Status     string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// discount
	DiscountType  string  `protobuf:"bytes,4,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float64 `protobuf:"fixed64,5,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinOrder      float64 `protobuf:"fixed64,6,opt,name=min_order,json=minOrder,proto3" json:"min_order,omitempty"`
	MaxDiscount   float64 `protobuf:"fixed64,7,opt,name=max_discount,json=maxDiscount,proto3" json:"max_discount,omitempty"`
	// targeting
	ProductType string `protobuf:"bytes,8,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	// usage
	MaxUsage   int32 `protobuf:"varint,9,opt,name=max_usage,json=maxUsage,proto3" json:"max_usage,omitempty"`
	UsageCount int32 `protobuf:"varint,10,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	// validity
	ValidFrom     string `protobuf:"bytes,11,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       string `protobuf:"bytes,12,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCoupon) Reset() {
	*x = UserCoupon{}
	mi := &file_proto_order_service_call_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoupon) ProtoMessage() {}

func (x *UserCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_call_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoupon.ProtoReflect.Descriptor instead.
func (*UserCoupon) Descriptor() ([]byte, []int) {
	return file_proto_order_service_call_proto_rawDescGZIP(), []int{8}
}

func (x *UserCoupon) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCoupon) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *UserCoupon) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserCoupon) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *UserCoupon) GetDiscountValue() float64 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *UserCoupon) GetMinOrder() float64 {
	if x != nil {
		return x.MinOrder
	}
	return 0
}

func (x *UserCoupon) GetMaxDiscount() float64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *UserCoupon) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *UserCoupon) GetMaxUsage() int32 {
	if x != nil {
		return x.MaxUsage
	}
	return 0
}

func (x *UserCoupon) GetUsageCount() int32 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *UserCoupon) GetValidFrom() string {
	if x != nil {
		return x.ValidFrom
	}
	return ""
}

func (x *UserCoupon) GetValidTo() string {
	if x != nil {
		return x.ValidTo
	}
	return ""
}

var File_proto_order_service_call_proto protoreflect.FileDescriptor

const file_proto_order_service_call_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/order_service_call.proto\x12\n" +
	"usercoupon\"0\n" +
	"\x15GetUserCouponsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"J\n" +
	"\x16GetUserCouponsResponse\x120\n" +
	"\acoupons\x18\x01 \x03(\v2\x16.usercoupon.UserCouponR\acoupons\"Q\n" +
	"\x15ValidateCouponRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x02 \x01(\tR\n" +
	"couponCode\"\x83\x01\n" +
	"\x16ValidateCouponResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12.\n" +
	"\x06coupon\x18\x03 \x01(\v2\x16.usercoupon.UserCouponR\x06coupon\"P\n" +
	"\x14ReserveCouponRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x02 \x01(\tR\n" +
	"couponCode\"V\n" +
	"\x15ReserveCouponResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"P\n" +
	"\x14ReleaseCouponRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x02 \x01(\tR\n" +
	"couponCode\"V\n" +
	"\x15ReleaseCouponResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x85\x03\n" +
	"\n" +
	"UserCoupon\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x02 \x01(\tR\n" +
	"couponCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rdiscount_type\x18\x04 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x05 \x01(\x01R\rdiscountValue\x12\x1b\n" +
	"\tmin_order\x18\x06 \x01(\x01R\bminOrder\x12!\n" +
	"\fmax_discount\x18\a \x01(\x01R\vmaxDiscount\x12!\n" +
	"\fproduct_type\x18\b \x01(\tR\vproductType\x12\x1b\n" +
	"\tmax_usage\x18\t \x01(\x05R\bmaxUsage\x12\x1f\n" +
	"\vusage_count\x18\n" +
	" \x01(\x05R\n" +
	"usageCount\x12\x1d\n" +
	"\n" +
	"valid_from\x18\v \x01(\tR\tvalidFrom\x12\x19\n" +
	"\bvalid_to\x18\f \x01(\tR\avalidTo2\xf1\x02\n" +
	"\x11UserCouponService\x12W\n" +
	"\x0eGetUserCoupons\x12!.usercoupon.GetUserCouponsRequest\x1a\".usercoupon.GetUserCouponsResponse\x12W\n" +
	"\x0eValidateCoupon\x12!.usercoupon.ValidateCouponRequest\x1a\".usercoupon.ValidateCouponResponse\x12T\n" +
	"\rReserveCoupon\x12 .usercoupon.ReserveCouponRequest\x1a!.usercoupon.ReserveCouponResponse\x12T\n" +
	"\rReleaseCoupon\x12 .usercoupon.ReleaseCouponRequest\x1a!.usercoupon.ReleaseCouponResponseBHZFdift_user_insentive/user-coupon-service/proto/pb/usercoupon;usercouponb\x06proto3"

var (
	file_proto_order_service_call_proto_rawDescOnce sync.Once
	file_proto_order_service_call_proto_rawDescData []byte
)

func file_proto_order_service_call_proto_rawDescGZIP() []byte {
	file_proto_order_service_call_proto_rawDescOnce.Do(func() {
		file_proto_order_service_call_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_service_call_proto_rawDesc), len(file_proto_order_service_call_proto_rawDesc)))
	})
	return file_proto_order_service_call_proto_rawDescData
}

var file_proto_order_service_call_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_order_service_call_proto_goTypes = []any{
	(*GetUserCouponsRequest)(nil),  // 0: usercoupon.GetUserCouponsRequest
	(*GetUserCouponsResponse)(nil), // 1: usercoupon.GetUserCouponsResponse
	(*ValidateCouponRequest)(nil),  // 2: usercoupon.ValidateCouponRequest
	(*ValidateCouponResponse)(nil), // 3: usercoupon.ValidateCouponResponse
	(*ReserveCouponRequest)(nil),   // 4: usercoupon.ReserveCouponRequest
	(*ReserveCouponResponse)(nil),  // 5: usercoupon.ReserveCouponResponse
	(*ReleaseCouponRequest)(nil),   // 6: usercoupon.ReleaseCouponRequest
	(*ReleaseCouponResponse)(nil),  // 7: usercoupon.ReleaseCouponResponse
	(*UserCoupon)(nil),             // 8: usercoupon.UserCoupon
}
var file_proto_order_service_call_proto_depIdxs = []int32{
	8, // 0: usercoupon.GetUserCouponsResponse.coupons:type_name -> usercoupon.UserCoupon
	8, // 1: usercoupon.ValidateCouponResponse.coupon:type_name -> usercoupon.UserCoupon
	0, // 2: usercoupon.UserCouponService.GetUserCoupons:input_type -> usercoupon.GetUserCouponsRequest
	2, // 3: usercoupon.UserCouponService.ValidateCoupon:input_type -> usercoupon.ValidateCouponRequest
	4, // 4: usercoupon.UserCouponService.ReserveCoupon:input_type -> usercoupon.ReserveCouponRequest
	6, // 5: usercoupon.UserCouponService.ReleaseCoupon:input_type -> usercoupon.ReleaseCouponRequest
	1, // 6: usercoupon.UserCouponService.GetUserCoupons:output_type -> usercoupon.GetUserCouponsResponse
	3, // 7: usercoupon.UserCouponService.ValidateCoupon:output_type -> usercoupon.ValidateCouponResponse
	5, // 8: usercoupon.UserCouponService.ReserveCoupon:output_type -> usercoupon.ReserveCouponResponse
	7, // 9: usercoupon.UserCouponService.ReleaseCoupon:output_type -> usercoupon.ReleaseCouponResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_order_service_call_proto_init() }
func file_proto_order_service_call_proto_init() {
	if File_proto_order_service_call_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_service_call_proto_rawDesc), len(file_proto_order_service_call_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_service_call_proto_goTypes,
		DependencyIndexes: file_proto_order_service_call_proto_depIdxs,
		MessageInfos:      file_proto_order_service_call_proto_msgTypes,
	}.Build()
	File_proto_order_service_call_proto = out.File
	file_proto_order_service_call_proto_goTypes = nil
	file_proto_order_service_call_proto_depIdxs = nil
}
