app:
  name: user-coupon-service

http:
  port: "8080"

grpc:
  address: ":50051"

database:
  dsn: "postgres://postgres:password@localhost:5432/coupon?sslmode=disable"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: 30m

nats:
  url: "nats://localhost:4222"
  stream: "COUPON_STREAM"
  subject: "coupon.events"